name: Pytest

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout repository
      - uses: actions/checkout@v2 

      # setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      # install libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # run unit-tests
      - name: Run tests
        env:
          PROJECT_HOME: /home/runner/work/lisp-py/lisp-py
          PYTHONPATH: /home/runner/work/lisp-py/lisp-py
        run: |
          pytest tests --cov=lisp --cov-report=term-missing --junitxml=pytest.xml | tee pytest-coverage.txt
        continue-on-error: true

      # commen test and coverage results to Pull-Request
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml